name: Node.js CI
on:
  pull_request:
    branches: "**"
  push:
    branches: "**"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.6.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Run CI command
        run: npm ci

      - name: Check linting
        run: npm run lint

      - name: Run prettier
        run: npm run format:check:ci

      # - name: Run the tests
      #   run: npm run test

      - name: Build
        run: npm run build
